### ISSUE TITLE
highPressureSteam issue

### ISSUE THREAD

**Issue by baifeiajdj** [mordgren/GTCA#5]
[Uploading crash-2024-11-16_16.05.20-client.txt…]()

**Comment by FunnyBunny14** [comment]
Caused by: java.lang.NoSuchMethodError: 'com.lowdragmc.lowdraglib.side.fluid.FluidStack com.gregtechceu.gtceu.api.data.chemical.material.Material.getFluid(long)'
	at net.mordgren.gtca.common.data.recipes.fuel.AltSteam.highPressureSteam(AltSteam.java:22) ~[gtca-1.1.0b-hotfix1.jar%23839!/:1.1.0b-hotfix1] {re:classloading}
	at net.mordgren.gtca.common.data.recipes.fuel.AltSteam.init(AltSteam.java:16) ~[gtca-1.1.0b-hotfix1.jar%23839!/:1.1.0b-hotfix1] {re:classloading}
	at net.mordgren.gtca.common.data.GTCARecipeInit.init(GTCARecipeInit.java:18) ~[gtca-1.1.0b-hotfix1.jar%23839!/:1.1.0b-hotfix1] {re:classloading}
	at net.mordgren.gtca.GTCAAddon.addRecipes(GTCAAddon.java:42) ~[gtca-1.1.0b-hotfix1.jar%23839!/:1.1.0b-hotfix1] {re:classloading}
	at com.gregtechceu.gtceu.common.data.GTRecipes.lambda$recipeAddition$1(GTRecipes.java:90) ~[gtceu-1.20.1-1.5.4.jar%23840!/:1.5.4] {re:classloading}

**Comment by mordgren** [comment]
mod updated, check my latest discord posts or releases on github
